{"uuid": "7fec95bb-46a8-43ec-b501-3536196d4541", "children": ["e8fbe745-03f2-4985-94f9-0c41450574d0"], "befores": [{"name": "test_register", "status": "broken", "statusDetails": {"message": "KeyError: 'err_code'\n", "trace": "  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\THTF\\PycharmProjects\\autotest\\src\\test\\case\\test_regandlogin.py\", line 25, in test_register\n    err_code=s[\"data\"][\"err_code\"]\n"}, "start": 1572852081651, "stop": 1572852081761}], "start": 1572852081651, "stop": 1572852081853}