{"uuid": "45dc5515-623a-4c80-8ea6-7471f4e96abc", "children": ["f553d656-0967-482e-a02f-7c4276c6ae25"], "befores": [{"name": "test_register", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0\n  -1\n  +0\n", "trace": "  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\THTF\\.jenkins\\workspace\\autotest\\src\\test\\case\\test_regandlogin.py\", line 29, in test_register\n    assert err_code  ==0\n"}, "start": 1572853910839, "stop": 1572853910981}], "start": 1572853910839, "stop": 1572853910997}