{"uuid": "7e466311-0498-45cb-bd2c-2bee4c76d8d1", "children": ["270f4c80-9f53-42b8-ab60-8e133ec615ed"], "befores": [{"name": "test_register", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0\n  -1\n  +0\n", "trace": "  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\THTF\\PycharmProjects\\autotest5\\src\\test\\case\\test_regandlogin.py\", line 29, in test_register\n    assert err_code  ==0\n"}, "start": 1572600603077, "stop": 1572600603194}], "start": 1572600603077, "stop": 1572600603211}