{"uuid": "97d6722d-efd6-49f3-9483-43167a7c95d2", "children": ["96b9e01a-6099-473f-84f3-9ccd9545c10b"], "befores": [{"name": "test_register", "status": "broken", "statusDetails": {"message": "KeyError: 'err_code'\n", "trace": "  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\THTF\\PycharmProjects\\autotest5\\src\\test\\case\\test_regandlogin.py\", line 25, in test_register\n    err_code=s[\"data\"][\"err_code\"]\n"}, "start": 1572601354914, "stop": 1572601355012}], "start": 1572601354914, "stop": 1572601355023}