{"uuid": "7d4d8acb-f675-46a8-b127-e61d02626a8b", "children": ["7c53bf3f-9f73-4e44-a7f9-0be0ed6bff04"], "befores": [{"name": "test_register", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0\n  -1\n  +0\n", "trace": "  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\THTF\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\THTF\\PycharmProjects\\autotest5\\src\\test\\case\\test_regandlogin.py\", line 29, in test_register\n    assert err_code  ==0\n"}, "start": 1572600679207, "stop": 1572600679351}], "start": 1572600679207, "stop": 1572600679356}